### ISSUE TITLE
ember-cli-password-strength updates

### ISSUE THREAD

**Issue by elwayman02** [linc-technologies/ember-paper-password#1]
In case you weren't aware, we just released a new version of e-c-p-s that loads the library async so apps don't have to include it in the main bundle! You can find the release notes [here](https://github.com/elwayman02/ember-cli-password-strength/releases/tag/v2.0.0), and details of how to use it in this addon in the README.

**Comment by pauln** [comment]
Thanks for the heads up, @elwayman02 - I'll look at updating soon.

**Comment by matthewhartstonge** [comment]
fixed via #5
